# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'Stack Reader' do
	pod 'AFNetworking', '~> 2.5'
end

target 'Stack ReaderTests' do

end

target 'Stack ReaderUITests' do

end

